apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dou-db
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-prd
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dou-job-logs
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-prd
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dou-api
  name: dou-api
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dou-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dou-api
    spec:
      containers:
        - image: ghcr.io/gestaogovbr/dou-api:latest
          imagePullPolicy: Always
          name: dou-api
          env:
            - name: INLABS_EMAIL
              valueFrom:
                secretKeyRef:
                  name: dou-job-credentials
                  key: INLABS_EMAIL
            - name: INLABS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dou-job-credentials
                  key: INLABS_PASSWORD
            - name: SLACK_BOT_URL
              valueFrom:
                secretKeyRef:
                  name: dou-job-credentials
                  key: SLACK_BOT_URL
            - name: FLASK_ENV
              value: production
          volumeMounts:
            - name: dou-db
              mountPath: /dou-api/data
            - name: dou-job-logs
              mountPath: /var/log
          ports:
          - containerPort: 5057
            protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 400m
              memory: 400Mi
      volumes:
        - name: dou-db
          persistentVolumeClaim:
            claimName: dou-db
        - name: dou-job-logs
          persistentVolumeClaim:
            claimName: dou-job-logs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dou-api
  name: dou-api-service
  namespace: airflow
spec:
  selector:
    app: dou-api
  ports:
    - port: 5057
      protocol: TCP
      targetPort: 5057
  type: LoadBalancer
